[package]
name = "rust_classifiers"
version = "0.1.0"
authors = ["dbyr <david.michael.byrne17@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
timely = "*"
timely_communication = "*"
abomonation = "*"
