[package]
name = "rust_classifiers"
version = "0.1.0"
authors = ["dbyr <david.michael.byrne17@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
mpi = "0.5"
mpi-sys = "0.1"
large_int = "0.2.2"
